"""add nevera y derivations

Revision ID: dc053396f68b
Revises: f70ac381b78a
Create Date: 2026-09-26 22:02:28.803518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dc053396f68b'
down_revision: Union[str, None] = 'f70ac381b78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nevera_rations')
    op.drop_table('derivations')
    op.drop_table('shift_assignments')
    op.drop_table('shifts')
    op.alter_column('batches', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('batches', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'disponible'::character varying"))
    op.alter_column('batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deliveries', 'family_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('deliveries', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('families', 'adults',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('families', 'minors',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('families', 'site',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('families', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('families', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('families', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('families', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('families', 'site',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('families', 'minors',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('families', 'adults',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deliveries', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('deliveries', 'family_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('batches', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'disponible'::character varying"))
    op.alter_column('batches', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shift_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['vehiculo'::character varying, 'clasificacion'::character varying, 'cestas'::character varying, 'puerta'::character varying]::text[])", name='ck_shifts_role_valid'),
    sa.CheckConstraint('capacity >= 1', name='ck_shifts_capacity_positive'),
    sa.PrimaryKeyConstraint('id', name='shifts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shift_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('attended', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='shift_assignments_shift_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shift_assignments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shift_assignments_pkey'),
    sa.UniqueConstraint('shift_id', 'user_id', name='uq_shift_user')
    )
    op.create_table('derivations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reference_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('person_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('served_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rations >= 1', name='ck_derivations_rations_pos'),
    sa.PrimaryKeyConstraint('id', name='derivations_pkey'),
    sa.UniqueConstraint('reference_code', name='derivations_reference_code_key')
    )
    op.create_table('nevera_rations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('target_rations', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True),
    sa.Column('served_rations', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nevera_rations_pkey')
    )
    # ### end Alembic commands ###
