export const SITE_CONFIG = {
  ong: {
    name: "XAMA-ONG",
    fullName: "XAMA-ONG · Asociación sin ánimo de lucro",
    tagline: "Recuperamos alimentos, alimentamos esperanza",
    bizumPhone: "600 000 000",
    iban: "ES00 0000 0000 0000 0000 0000",
    ibanHolder: "XAMA ONG",
    email: "hola@xamaong.cat",
    phone: "977 000 000",
    address: "Reus · Tarragona (España)",
    city: "Reus",
    bankName: "CaixaBank",
    social: {
      instagram: "https://www.instagram.com/xamaong/?hl=es",
      twitter: "https://x.com/XAMA_Catalunya?lang=es",
      facebook: "https://www.facebook.com/xamacatalunya/?locale=es_ES",
      youtube: "https://www.youtube.com/hashtag/xama",
    },
    externalLinks: [
      {
        label: "Xarxa d'Ajuda Mútua Alimentària",
        url: "https://comunalitats.cat/recursos/bones-practiques/xarxa-dajuda-mutua-alimentaria",
      },
    ],
    sponsors: [
      { name: "Diputació Tarragona" },
      { name: "Xarxa Santa Tecla" },
      { name: "Espigoladors" },
      { name: "INS Domènech i Montaner" },
      { name: "Banc dels Aliments" },
      { name: "ALDI" },
      { name: "Centre de rehabilitació VISIÓN" },
      { name: "Fundació Pare Manel" },
      { name: "FIJJD" },
      { name: "Samasa" },
      { name: "Veritas" },
      { name: "Zero Waste Europe" },
    ],
  },
  developer: {
    name: "Manuel Casimiro Carrasco",
    role: "Desarrollador Web",
    location: "Reus, Tarragona (España)",
    email: "manuelcasimirocarrasco@example.com",
    bio: "Desarrollador web con experiencia en el campo de la tecnología.",
    longBio: "Esa pasión lo llevó a estudiar una carrera relacionada con el desarrollo web.",
    presentationUrl: "https://silly-boba-dc057e.netlify.app/",
    projects: [
      { label: "Proyecto 1", url: "https://rad-dolphin-182dfb.netlify.app/" },
      { label: "Proyecto 2", url: "https://unique-biscochitos-31bcea.netlify.app/" },
    ],
  },
  legal: {
    lastUpdated: "27 de septiembre de 2026",
    jurisdiction: "España",
    contactEmail: "hola@xamaong.cat",
  },
  testimonials: [
    { quote: "Empecé hace dos años y ya no puedo parar.", author: "María", role: "Voluntaria · Reus" },
    { quote: "Llegamos al país sin nada. XAMA nos ayudó.", author: "Anónimo", role: "Familia · Tarragona" },
    { quote: "Colaboramos desde 2024.", author: "Panificadora del Baix Camp", role: "Empresa donante" },
  ],
  pillars: [
    { icon: "Apple", title: "Recuperamos", desc: "Excedentes de comercios locales, agricultores, empresas y campañas solidarias." },
    { icon: "HandHeart", title: "Repartimos", desc: "Preparamos cestas semanales y las hacemos llegar a las familias." },
    { icon: "Leaf", title: "Cuidamos", desc: "Reducimos el desperdicio alimentario y medimos el CO₂ evitado." },
    { icon: "BarChart3", title: "Transparencia", desc: "Publicamos cifras en tiempo real: kg recuperados, familias atendidas." },
  ],
  companyBenefits: [
    "Recogida semanal programada de vuestro excedente",
    "Certificado de impacto ambiental (CO₂ evitado) para vuestra memoria ESG",
    "Certificado de donación deducible fiscalmente (Ley 49/2002)",
    "Mención como empresa colaboradora en nuestras memorias anuales",
    "Sin coste: nosotros ponemos el transporte y los voluntarios",
  ],
} as const;
